[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.filesystem = spiffs

build_flags =
    -DCORE_DEBUG_LEVEL=3
    -Wl,-zmuldefs
    -w

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    crankyoldgit/IRremoteESP8266@^2.8.6
    fastled/FastLED@^3.6.0
    t-vk/ESP32 BLE Keyboard@^0.3.2
