[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino

board_build.partitions = huge_app.csv
monitor_speed = 115200
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Wl,-zmuldefs
    -Iinclude
    -std=gnu++17
    -DFASTLED_ESP32_I2S=true

lib_deps =
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.16.1
    fastled/FastLED@^3.7.0
    earlephilhower/ESP8266Audio@^1.9.7

lib_ldf_mode = deep+
